repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest tests/
        language: system
        files: ^tests/
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.10.0
      hooks:
      -   id: mypy
  -   repo: https://github.com/psf/black
      rev: 22.10.0
      hooks:
      -   id: black
