name: Publish Python Package

on:
  push:
    tags:
      - 'v*.*.*' # This triggers the workflow on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install

      - name: Run tests
        run: poetry run pytest

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.0
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            Changes in this release:
            ${{ steps.get_changes.outputs.changes }}
          draft: false
          prerelease: false

      - name: Get commit messages
        id: get_changes
        run: |
          echo "changes=$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:'- %s')" >> $GITHUB_ENV
